engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  #brakeman:
  #  enabled: true
    #exclude_fingerprints:
    #- 08c185b3f764f262539a1f76997d3a89
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      #mass_threshold: 30
      - javascript
ratings:
  paths:
  - src/**
  - "**.py"
  - "**.js"
  - "**.html"
exclude_paths:
  - src/spicy/core/siteskin/static/**
  - "**/fixtures/**"
  - src/spicy/core/admin/static/**
  - src/spicy/templates/**
  - "**/locale/**"
  - docs/**
  - sql/**
