types:   
  - test 
  - deploy
  

test_app:
  type: test
  script: 
    #- docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    #- docker pull "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - echo "test $CI_BUILD_REF_NAME"
    - runtests.sh
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
    
    
trigger_build:
  stage: deploy
  script:
    - curl -X POST -F token=$SPICYCRM_TRIGGER_TOKEN -F ref=$CI_BUILD_REF_NAME https://gitlab.com/api/v3/projects/1624463/trigger/builds
  dependencies:
    - test_app
