language: python
python:
  - "2.7"
install: "pip install -r requirements_dev.txt"
script: DJANGO_SETTINGS_MODULE="spicy.core.profile.tests.settings" PYTHONPATH="${PYTHONPATH}:$(pwd)/src" python -m unittest discover
