language: python

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7

sudo: false

install: 
  - pip install -U pip>=8.0
  - pip install .
  - pip install -r requirements_dev.txt

script: 
  - ./runtests.sh
  
after_success: coveralls
